### PR TITLE
Changed DB names for SIARDDK testing and enabled SIARDDK tests

### PR DESCRIPTION
**Pull request by andreaskring**
To see if this solves the problem with the failing SIARDDK tests...

### CODE REVIEW

**Comment by chalkos** [comment]
@andreaskring try also changing the username.

**Comment by chalkos** [comment]
Can you try rebasing on my branch bf-permissive?
master branch tests are failing so the siard tests may already be fixed. bf-permissive fixes the tests

**Comment by chalkos** [comment]
@andreaskring nevermind that. it is easier for me to merge your changes. I'll do that when possible and notify you.

**Comment by chalkos** [comment]
@andreaskring I was able to fix it. After changing the name I had to increase the maximum heap memory available during testing. The tests are enabled on #190, I will be merging it soon and creating a new release.

**Comment by andreaskring** [comment]
@chalkos Super! Thanks - great that you found the problem - cool that the tests are now running without error.

**Pull request closed without merging**
