### PR TITLE
SIARDDK import module and round-trip tests

### PR DESCRIPTION
**Pull request by andreaskring**
The SIARDDK import module made by @ThomasKristensen along with some nice round-trip tests.

### CODE REVIEW

**Comment by chalkos** [comment]
This is not compiling in java 7, please see the error at the end of https://travis-ci.org/keeps/db-preservation-toolkit/jobs/112804789

**Comment by andreaskring** [comment]
Hmm - I do not get any errors when I compile this in Java 7:

`$ javac -version` returns
`javac 1.7.0_80`

After running `mvn clean compile` I get

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Database Preservation Toolkit ...................... SUCCESS [  0.102 s]
[INFO] dbptk-model ........................................ SUCCESS [  1.482 s]
[INFO] dbptk-core ......................................... SUCCESS [  6.077 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.754 s
[INFO] Finished at: 2016-03-04T10:30:56+01:00
[INFO] Final Memory: 27M/1000M
[INFO] ------------------------------------------------------------------------

@chalkos Do you mind trying to compile it with Java 7 locally on your machine to see if you run into any problems?

**Comment by chalkos** [comment]
@andreaskring I'm not at my working computer, could you try to rename (or remove) the `.m2` folder in your home directory and try the `mvn clean package` again? This folder is used by maven and may contain something that Travis' does not.

**Comment by andreaskring** [comment]
@chalkos I have tried what you suggested, but it still compiles fine in Java 7:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Database Preservation Toolkit ...................... SUCCESS [  0.127 s]
[INFO] dbptk-model ........................................ SUCCESS [ 28.686 s]
[INFO] dbptk-core ......................................... SUCCESS [ 35.513 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min
[INFO] Finished at: 2016-03-07T08:30:42+01:00
[INFO] Final Memory: 56M/1114M
[INFO] ------------------------------------------------------------------------

**Comment by chalkos** [comment]
Thanks, I'll try to identify the problem

**Comment by chalkos** [comment]
@andreaskring @ThomasKristensen 
It fails in `SIARDDKMetadataImportStrategy#getNumberOfTblRows`, in the line 221: `return numRows.longValueExact();`

Turns out `#longValueExact` does not exist in java 7:
https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html
And is present in java 8:
https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html

**Pull request merged**
