### PR TITLE
Fixes for a number og bugs

### PR DESCRIPTION
**Pull request by andreaskring**
Fixes for issues #222 #223 #254 #256 #259

### CODE REVIEW

**Comment by andreaskring** [comment]
@chalkos I can see above that the automatic checks have failed... when I run `$ mvn clean test` they all pass - it seems as if the test server is having trouble downloading some dependencies?

**Comment by chalkos** [comment]
Travis only compiles core and model, and downloads the other dependencies (bindings) from http://artifactory.keep.pt/ but since you updated bindings-siard-dk version, it failed because that version was not in the artifactory. I have built and uploaded it there and travis passes.

Phillip is still testing your fixes, correct?

**Comment by PhillipTommerholt** [comment]
Yes - I hope I will be done testing Friday afternoon.

**Comment by andreaskring** [comment]
Hmm - I can't see the latest changes from the branch fixesIssues_222_223_254_256_259... maybe GitHub is just slow...

**Comment by andreaskring** [comment]
@chalkos This pull request does not seem to pick up the latest change in the Magenta branch (which it usually would do as far as I remember...) - would you like me to make a new pull request instead?

**Comment by chalkos** [comment]
@andreaskring I looked it up on google and doesn't seem to be a common issue. It doesn't seem like a mistake on your part either. You can also try to rebase/merge the changes in master and push again... if it does not work, create a new one and reference this one.

**Comment by andreaskring** [comment]
@chalkos I can see the latest commits in the list above now, so it seems as if the issue was just do to GitHub being slow. You can update the SIARDDK bindings now (and then the tests should pass) and then this pull request should be ready for merging.

**Comment by chalkos** [comment]
@andreaskring tests are still failing, can you try rebasing/merging master? It seems to be related to some tests that I fixed.

**Comment by andreaskring** [comment]
@chalkos Ok - I have merged master into the branch now (tests are passing here when I do `$ mvn clean test`)

**Comment by chalkos** [comment]
that is expected, since `mvn clean test` only runs the "no dependencies" tests. it does not run the roundtrip tests that use postgresql and are failing on travis. we should have results in a few seconds.

**Comment by andreaskring** [comment]
@chalkos Ok - done. The new check is running now

**Comment by chalkos** [comment]
The tests failed again. I just checked and the tests pass on master, so the "bad" change is in this pull request.

**Comment by chalkos** [comment]
@andreaskring try mergin my branch `bf-magenta-fix-tests`. this is fixed in there

**Comment by andreaskring** [comment]
@chalkos Thanks for this. Looks good here - the postgresql-siarddk tests are passing now. I have merged in your changes and have pushed the updated branch. Tests are running now.

**Comment by chalkos** [comment]
@andreaskring the tests passed. is this ready to merge or does it need to be sent to @PhillipTommerholt to test again after the recent changes?

**Comment by andreaskring** [comment]
@PhillipTommerholt is on leave at the moment, so he will not be here for a while - I think you should just merge the changes - @andersbonielsen is this ok with you?

**Comment by chalkos** [comment]
Rushing code merges already lead to problems once before. I prefer to wait for the new code to be tested.

**Comment by PhillipTommerholt** [comment]
@andreaskring 
I am ready to test it again. Do you have a jar-file which I can test?

**Comment by andreaskring** [comment]
@PhillipTommerholt Welcome back. You can download the jar from here: https://drive.google.com/file/d/0B8hAEqjI-ScYd3Z1SERUbDJlZFU/view?usp=sharing

**Comment by PhillipTommerholt** [comment]
Thanks and thanks :+1:

**Comment by chalkos** [comment]
I will have to merge this since I will be making some changes to the code structure. And it will be easier to fix any remaining problems after the code re-structuring than trying to merge these changes after they have been fully tested.

**Comment by PhillipTommerholt** [comment]
I managed to rerun before x-mas.
It behaved the same way it should. :+1: 
- Happy holidays @andreaskring @chalkos

**Comment by andreaskring** [comment]
@PhillipTommerholt @chalkos Great - thanks for testing! Merry x-mas to you guys too :-)

**Pull request merged**
