### PR TITLE
Added table filtering functionality for SIARDDK

### PR DESCRIPTION
**Pull request by andreaskring**
Added optional option to filter tables in SIARDDK export module in the same way as it is done in SIARD1 and SIARD2.

### CODE REVIEW

**Comment by chalkos** [comment]
Tests are failing but that's not new :) (and I think I already fixed these in some other branch).
The PR looks fine, is it ready to be merged or you want to add anything else?

**Comment by andreaskring** [comment]
I do not have anything to add for this pull request, so it should be ready to merge.

About the failing tests... the changes that I have just made is base on the latest commit to master branch at KEEPS - was I supposed to do this in another way (if so, I will fix it...)?

**Comment by chalkos** [comment]
Ok. Merging.

> was I supposed to do this in another way (if so, I will fix it...)?

Nope. The tests that are failing in this PR are my responsibility, don't worry about them.
But I suggest that you look into the SIARDDK tests that were failing (I disabled them to make tests pass).

**Comment by chalkos** [comment]
@andreaskring It just occurred to me the probable cause for the failing SIARD DK tests due to concurrency:

Testng is using concurrency at a class level. which means that the MySQL test class and the PostgreSQL test class run simultaneously. But it also means that the MySQLSIARDDK test class runs simultaneously with MySQL test class. Since both use the same databases (`dpttest` and `dpttest_siard`), it is probable to be used/overwritten by the concurrent test at some point. See this line: https://github.com/keeps/db-preservation-toolkit/blob/bf-travis-test-problem/dbptk-core/src/test/java/com/databasepreservation/testing/integration/roundtrip/MySqlSIARDDKTest.java#L27

Changing the database used by SIARD DK tests should be enough to fix the current problem. Can you try that? (to check if it is working: submitting a pull request will run the tests on travis)

**Comment by andreaskring** [comment]
@chalkos @PhillipTommerholt Previously, we added code that supported the table filtering functionality via this pull request, but looking at the latest code this feature has been disable for the SIARDDK export module: [see this](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-modules/dbptk-module-siard/src/main/java/com/databasepreservation/modules/siard/SIARDDKModuleFactory.java#L202). I must admit that I can't remember the history... do you guys remember why this was disabled again (I can't remember doing it)?

I'm planning on reenabling the feature in the Magenta fork - @chalkos : are you interested in a pull request when it has been fixed?

**Comment by chalkos** [comment]
@andreaskring please review the following commit: https://github.com/keeps/db-preservation-toolkit/commit/87e4f6e072f6008ec0cb7bb338dc479d380eecd8 (this is where that line was created, and it was already commented out)

**Comment by andreaskring** [comment]
@chalkos Thanks for the fast reply. Yes - you are right about that. I am remembering incorrectly then - I thought the table filtering functionality had been working for SIARDDK too, but this cannot not be the case according to the commit you are referencing. Anyway - I will fix this at some point in our fork - and also some other stuff along the way. Should I make a pull request or should I just leave new SIARDDK features/enhancements/bugfixes in our own DBPTK fork?

**Comment by chalkos** [comment]
You are welcome to make a pull request with the improvements. Thanks!

**Comment by andreaskring** [comment]
@chalkos @PhillipTommerholt My bad. The table filter is actually working for SIARDDK too - I must have been making some kind of mistake when I tested it earlier on. Sorry for in inconvenience.

**Pull request merged**
